// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksDirectory.Models;

#nullable disable

namespace ParksDirectory.Migrations
{
    [DbContext(typeof(ParksDirectoryContext))]
    partial class ParksDirectoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksDirectory.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Classification")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("MajorLandmarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Classification = "national park",
                            Location = "Oregon",
                            MajorLandmarks = "Crater Lake, Wizard Island",
                            Name = "Crater Lake",
                            YearFounded = 1902
                        },
                        new
                        {
                            ParkId = 2,
                            Classification = "national monument",
                            Location = "Oregon",
                            MajorLandmarks = "Lava Butte, Lava River Cave, Lava Cast Forest, Newberry Caldera, Big Obsidian Flow, Paulina Peak, East Lake, Paulina Lake",
                            Name = "Newberry National Volcanic Monument",
                            YearFounded = 1990
                        },
                        new
                        {
                            ParkId = 3,
                            Classification = "state park",
                            Location = "Oregon",
                            MajorLandmarks = "Smith Rock",
                            Name = "Smith Rock State Park",
                            YearFounded = 1960
                        },
                        new
                        {
                            ParkId = 4,
                            Classification = "state park",
                            Location = "Oregon",
                            MajorLandmarks = "Deschutes River Trail",
                            Name = "Tumalo State Park",
                            YearFounded = 1954
                        },
                        new
                        {
                            ParkId = 5,
                            Classification = "national forest",
                            Location = "Oregon",
                            MajorLandmarks = "Mount Jefferson, Mount Washington, the Three Sisters, Lava Lands, Metolius River, Cascade Lakes",
                            Name = "Deschutes National Forest",
                            YearFounded = 1908
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
